### ISSUE TITLE
Fix: Request getting timed out even after increasing the timeout period

### ISSUE THREAD

**Issue by nlok5923** [RizeLabs/Sample-Hardhat-Template#2]
```
ProviderError: request timed out
    at HttpProvider.request (/Users/nitanshulokhande/Documents/Projects/Blockchain-Projects/fhe-projects/Sample-Hardhat-Template/node_modules/hardhat/src/internal/core/providers/http.ts:96:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HardhatEthersProvider.estimateGas (/Users/nitanshulokhande/Documents/Projects/Blockchain-Projects/fhe-projects/Sample-Hardhat-Template/node_modules/@nomicfoundation/hardhat-ethers/src/internal/hardhat-ethers-provider.ts:246:27)
    at async /Users/nitanshulokhande/Documents/Projects/Blockchain-Projects/fhe-projects/Sample-Hardhat-Template/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:235:35
    at async Promise.all (index 0)
    at async HardhatEthersSigner._sendUncheckedTransaction (/Users/nitanshulokhande/Documents/Projects/Blockchain-Projects/fhe-projects/Sample-Hardhat-Template/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:256:7)
    at async HardhatEthersSigner.sendTransaction (/Users/nitanshulokhande/Documents/Projects/Blockchain-Projects/fhe-projects/Sample-Hardhat-Template/node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (/Users/nitanshulokhande/Documents/Projects/Blockchain-Projects/fhe-projects/Sample-Hardhat-Template/node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.voteProposal (/Users/nitanshulokhande/Documents/Projects/Blockchain-Projects/fhe-projects/Sample-Hardhat-Template/node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async main (/Users/nitanshulokhande/Documents/Projects/Blockchain-Projects/fhe-projects/Sample-Hardhat-Template/scripts/encryptedVoting.ts:32:11)
```

**Comment by nlok5923** [comment]
Facing this error while trying to deploy and run the vote method in SimpleVoting contract.

**Comment by nlok5923** [comment]
Increased timeout!
